using System.Collections.Generic;
using UnityEngine;
using Alexandria.ItemAPI;

namespace PlutoTheCat
{
    /// <summary>
    /// Frame-following fur for the Puffed Up passive. Every body frame Pluto can show while
    /// standing or moving has four fur layers (short, medium, long, jitter) generated by the art
    /// pipeline (tools/fur.py) on a canvas 4 px wider on each side and 4 px taller than the body.
    /// Sprites are named fur_{clip}_{frame:000}_{variant} and live in their own collection.
    /// </summary>
    public static class PlutoFur
    {
        public const int MarginX = 4;
        public const string ResourceRoot = "PlutoTheCat.Resources.Fur.";
        public static tk2dSpriteCollectionData Collection;
        private static readonly Dictionary<string, int> ids = new Dictionary<string, int>();
        public static int Count { get { return ids.Count; } }

        public static void Init()
        {
            GameObject holder = new GameObject("PlutoFurCollection");
            Object.DontDestroyOnLoad(holder);
            Collection = SpriteBuilder.ConstructCollection(holder, "PlutoFurCollection");
            string[] names = ResourceExtractor.GetResourceNames(typeof(Plugin).Assembly);
            for (int i = 0; i < names.Length; i++)
            {
                string n = names[i];
                if (!n.StartsWith(ResourceRoot) || !n.EndsWith(".png")) continue;
                string sprite = n.Substring(n.LastIndexOf('.', n.Length - 5) + 1);   // "fur_idle_001_2.png"
                sprite = sprite.Substring(0, sprite.Length - 4);
                Texture2D tex = ResourceExtractor.GetTextureFromResource(n, typeof(Plugin).Assembly);
                if (tex == null) continue;
                int id = SpriteBuilder.AddSpriteToCollection(tex, Collection, sprite);
                ids[sprite] = id;
            }
            Plugin.Log("fur layers: " + ids.Count);
        }

        /// <summary>Sprite id for a clip/frame/variant, or -1. Hand variants share the base clip's fur.</summary>
        public static int Lookup(string clip, int frame, int variant)
        {
            if (clip == null) return -1;
            if (clip.EndsWith("_twohands")) clip = clip.Substring(0, clip.Length - 9);
            else if (clip.EndsWith("_hand")) clip = clip.Substring(0, clip.Length - 5);
            int id;
            return ids.TryGetValue("fur_" + clip + "_" + (frame + 1).ToString("000") + "_" + variant, out id) ? id : -1;
        }
    }
}
