// GENERATED by tools/weapon_layout.py (run tools/make_art.py). Do not edit by hand.
// Player weapon attachment pixels, measured from the sprite's bottom-left; divide by 16 for units.
namespace PlutoTheCat
{
    public static class WeaponLayout
    {
        public const int KIBBLE_SACK_W = 32, KIBBLE_SACK_H = 18;
        public const int KIBBLE_SACK_HAND_X = 4, KIBBLE_SACK_HAND_Y = 5;
        public const int KIBBLE_SACK_MUZZLE_X = 29, KIBBLE_SACK_MUZZLE_Y = 9;
        public const int TAIYAKI_CANNON_W = 57, TAIYAKI_CANNON_H = 31;
        public const int TAIYAKI_CANNON_HAND_X = 21, TAIYAKI_CANNON_HAND_Y = 4;
        public const int TAIYAKI_CANNON_MUZZLE_X = 46, TAIYAKI_CANNON_MUZZLE_Y = 15;
        public const int KATANA_W = 43, KATANA_H = 33;
        public const int KATANA_HAND_X = 6, KATANA_HAND_Y = 13;
        public const int KATANA_MUZZLE_X = 41, KATANA_MUZZLE_Y = 13;
        public const int KATANA_SWING_W = 43, KATANA_SWING_H = 80;
        public const int KATANA_SWING_GRIP_X = 6, KATANA_SWING_GRIP_Y = 40;
        public const int KATANA_SWING_GRIP_OFFSET = 27;
        public const float KATANA_CASING_REACH_UNITS = 2.4f;
    }
}
