"""The one authored source for player weapon attachment numbers (grip, muzzle, canvases, katana swing and reach).

tools/make_art.py writes each gun frame's .jtk2d attach points from this table and generates
PlutoTheCat/src/WeaponLayout.cs from it; the gun classes read that file instead of hard-coding pixels.
tools/validate.py fails the build when the generated file is stale; tools/tests/test_weapon_layout.py checks
the table against the exported art. Pixels are measured from the sprite's bottom-left; one unit is 16 px.
"""
import os
from collections import OrderedDict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CS_PATH = os.path.join(ROOT, 'PlutoTheCat', 'src', 'WeaponLayout.cs')

WEAPONS = OrderedDict([
    # Royal Canin bag: the paw grips the bottom gusset (left end); kibble leaves the torn-open zip top (right end).
    ('kibble_sack', dict(sprite='pluto_kibble_sack', costume='normal', canvas=(32, 18), hand=(4, 5), muzzle=(29, 9))),
    # Spray Bottle: Pluto grips the bottle neck; mist leaves the right-facing sprayer nozzle.
    ('spray_bottle', dict(sprite='pluto_spray_bottle', costume='normal', canvas=(26, 20), hand=(10, 9), muzzle=(18, 16))),
    # Feather Teaser: grip at the pink handle, lure leaves the bell/feather end of the wand.
    ('feather_teaser', dict(sprite='pluto_feather_teaser', costume='normal', canvas=(40, 20), hand=(5, 10), muzzle=(36, 8))),
    # Golden taiyaki held like a pistol: grip under the belly, mini taiyaki leave the bean-filled mouth.
    ('taiyaki_cannon', dict(sprite='pluto_taiyaki_cannon', costume='samurai', canvas=(57, 31), hand=(21, 4), muzzle=(46, 15))),
    # Katana: handle grip and blade tip. The swing (fire clip) sits on a taller canvas with the grip at swing_grip;
    # KatanaGun moves those frames down by (swing_grip.y - hand.y) so the grip stays in Pluto's paw.
    # Swing radius = 1.85 x |Casing - PrimaryHand| (Gun.HandleHeroSwordSlash); KatanaGun pushes Casing out to
    # casing_reach_units after the sprite setup, so the jtk2d muzzle stays on the blade tip for the art.
    ('katana', dict(sprite='pluto_katana', costume='samurai', canvas=(43, 33), hand=(6, 13), muzzle=(41, 13),
                    swing_canvas=(43, 80), swing_grip=(6, 40), casing_reach_units=2.4)),
])

HERO_SWORD_RADIUS_FACTOR = 1.85   # Gun.HandleHeroSwordSlash, used by the previews only


def swing_grip_offset(spec):
    return spec['swing_grip'][1] - spec['hand'][1]


def swing_radius_px(spec):
    return HERO_SWORD_RADIUS_FACTOR * abs(spec['casing_reach_units'] * 16 - spec['hand'][0])


def spec_for_frame(filename):
    """WEAPONS entry for a WeaponCollection frame name, or None."""
    for spec in WEAPONS.values():
        if filename.startswith(spec['sprite'] + '_'):
            return spec
    return None


def _f(v):
    s = repr(float(v))
    return s + 'f'


def layout_cs():
    lines = [
        '// GENERATED by tools/weapon_layout.py (run tools/make_art.py). Do not edit by hand.',
        '// Player weapon attachment pixels, measured from the sprite\'s bottom-left; divide by 16 for units.',
        'namespace PlutoTheCat',
        '{',
        '    public static class WeaponLayout',
        '    {',
    ]
    for key, spec in WEAPONS.items():
        p = key.upper()
        lines.append('        public const int %s_W = %d, %s_H = %d;' % (p, spec['canvas'][0], p, spec['canvas'][1]))
        lines.append('        public const int %s_HAND_X = %d, %s_HAND_Y = %d;' % (p, spec['hand'][0], p, spec['hand'][1]))
        lines.append('        public const int %s_MUZZLE_X = %d, %s_MUZZLE_Y = %d;' % (p, spec['muzzle'][0], p, spec['muzzle'][1]))
        if 'swing_grip' in spec:
            lines.append('        public const int %s_SWING_W = %d, %s_SWING_H = %d;' % (p, spec['swing_canvas'][0], p, spec['swing_canvas'][1]))
            lines.append('        public const int %s_SWING_GRIP_X = %d, %s_SWING_GRIP_Y = %d;' % (p, spec['swing_grip'][0], p, spec['swing_grip'][1]))
            lines.append('        public const int %s_SWING_GRIP_OFFSET = %d;' % (p, swing_grip_offset(spec)))
            lines.append('        public const float %s_CASING_REACH_UNITS = %s;' % (p, _f(spec['casing_reach_units'])))
    lines += ['    }', '}', '']
    return '\n'.join(lines)


def write(path=CS_PATH):
    with open(path, 'w') as fh:
        fh.write(layout_cs())
    return path


if __name__ == '__main__':
    print(write())
